#!/usr/bin/env python3
"""card.src.svg (live text) -> card.svg (text outlined).

The committed card.svg must not depend on an installed font, and the source must
stay editable when the copy changes, so both files exist and this keeps them in
agreement. Glyph paths are re-emitted with our own ids and formatting rather than
pasted from Inkscape's output, so the result is byte-stable across Inkscape
versions and across runs.

Note Inkscape emits a <g> of paths when a string carries more than one fill (the
wordmark, whose scope is muted) and a bare <path> when it carries one (the
tagline). Both shapes are handled; assuming either one silently loses a string.
"""
import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "card.src.svg"
OUT = HERE / "card.svg"
TMP = Path("/tmp/etherplay-connect-fc")
SVG = "{http://www.w3.org/2000/svg}"

LABELS = {
    "wordmark": ("@etherplay/connect", "#f4f6fb"),
    "tagline": ("Built-in wallet, hosted account, or connection only. One store.", "#8e97a8"),
}


def env_with_vendored_fonts():
    TMP.mkdir(parents=True, exist_ok=True)
    (TMP / "fonts.conf").write_text(
        '<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd">\n'
        f"<fontconfig><dir>{HERE / 'fonts'}</dir><dir>/usr/share/fonts</dir>"
        f"<cachedir>{TMP / 'cache'}</cachedir></fontconfig>\n"
    )
    env = dict(os.environ)
    env["FONTCONFIG_FILE"] = str(TMP / "fonts.conf")
    return env


def fill_of(el, default):
    style = el.get("style", "")
    m = re.search(r"fill:\s*(#[0-9a-fA-F]{3,8})", style)
    if m:
        return m.group(1)
    return el.get("fill", default)


outlined = TMP / "outlined.svg"
subprocess.run(["inkscape", str(SRC), "--export-text-to-path", "--export-plain-svg",
                "-o", str(outlined)], check=True, capture_output=True,
               env=env_with_vendored_fonts())

root = ET.parse(outlined).getroot()
by_id = {el.get("id"): el for el in root.iter() if el.get("id")}

groups = {}
for name, (_label, default_fill) in LABELS.items():
    el = by_id.get(name)
    if el is None:
        sys.exit(f"error: no outlined element with id={name}")
    if el.tag == f"{SVG}path":
        members = [el]
    elif el.tag == f"{SVG}g":
        members = [c for c in el.iter() if c.tag == f"{SVG}path"]
    else:
        sys.exit(f"error: id={name} outlined to unexpected <{el.tag}>")
    lines = []
    for p in members:
        d = " ".join((p.get("d") or "").split())
        if not d:
            continue
        f = fill_of(p, fill_of(el, default_fill))
        attr = f' fill="{f}"' if f != default_fill else ""
        lines.append(f'    <path{attr} d="{d}" />')
    if not lines:
        sys.exit(f"error: no glyph outlines found for {name}")
    groups[name] = lines

card = SRC.read_text()
card = card.replace(
    "  <desc>Card source with LIVE TEXT. card.svg is this with the text outlined; "
    "solve-card.py owns the numbers.</desc>",
    "  <desc>GENERATED by outline-text.py from card.src.svg. Do not hand-edit: edit the "
    "source and re-run build.sh. Text is outlined, so rendering needs no font.</desc>")

for name, (label, default_fill) in LABELS.items():
    pattern = re.compile(rf'  <text id="{name}".*?</text>', re.S)
    block = (f'  <g id="{name}" fill="{default_fill}" aria-label="{label}">\n'
             + "\n".join(groups[name]) + "\n  </g>")
    card, n = pattern.subn(lambda _m: block, card, count=1)
    if n != 1:
        sys.exit(f"error: could not splice {name} into the card")

OUT.write_text(card)
print(f"wrote {OUT.name}: "
      + ", ".join(f"{len(v)} {k} path(s)" for k, v in groups.items()))
